[colors.bright]
black = "#585b70"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#a6adc8"
yellow = "#f9e2af"

[colors.cursor]
cursor = "#f5e0dc"
text = "#1e1e2e"

[colors.normal]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.selection]
background = "#f5e0dc"
text = "#1e1e2e"

[env]
LANG = "en_US.UTF-8"

[font]
size = 8

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"

[window]
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 8
y = 6

[terminal]
